Initialize database and add signup feature
bibekmaharjan/practitioner-profile-backend pull request #1
Opened 2023-05-15 09:23 UTC by bibekmaharjan

## Description

* Add authRoutes to handle auth related routes.
* Add db and auth config.
* Add a controller to handle auth signup request.
* Add middleware to verify signup and schema.
* Initialize models and add model related to user auth.
* Add schema for auth.
* Add signup functionality

### Screenshot:

![image](https://github.com/bibekmaharjan/practitioner-profile-backend/assets/30655695/c24c51d5-40bf-46f6-a9b0-85dec03a7c52)

2023-05-15 16:39 UTC, sbimochan requested changes

2023-05-15 16:39 UTC, sbimochan commented on src/models/index.ts
> +db.user = user(sequelize, Sequelize);
are these even necessary?

2023-05-15 16:39 UTC, sbimochan commented on src/middleware/verifySignup.ts
> +const User = db.user;
can't we directly import User model from ../user? rather than db?

2023-05-15 16:39 UTC, sbimochan commented on src/middleware/verifySignup.ts
> +      return;
what about 
```suggestion
      return res.status(400).send({
        message: 'Sorry email already exists',
      });
```

2023-05-15 16:39 UTC, sbimochan commented on src/middleware/verifySignup.ts
> +  }).then((user) => {
refactor into try...catch and async...await

2023-05-15 16:39 UTC, sbimochan commented on src/models/user.ts
> +        type: Sequelize.STRING,
add unique: true if you're checking for duplicates in this app

2023-05-15 16:39 UTC, sbimochan commented on src/models/user.ts
> +    {
create for id (integer, primary key and autoincrement)

2023-05-15 16:39 UTC, sbimochan commented on src/utils/schemaValidator.ts
> +    console.log(data);
(Optional) Prevent console.log to be pushed in git. add some lints and pre commit hooks

2023-05-16 08:19 UTC, bibekmaharjan commented on src/models/index.ts
> +db.user = user(sequelize, Sequelize);
Those are not strictly necessary but it is done to assign references to the Sequelize instance and models to the db object as it will make the sequelize instance and models accessible from the single object `db` .

2023-05-16 08:21 UTC, bibekmaharjan commented on src/middleware/verifySignup.ts
> +const User = db.user;
Import is done in the above method due to the above reason assignment of references. We can import directly if we dont need to assign reference.

2023-05-23 04:44 UTC, sbimochan commented on src/controller/auth.ts
> +    res.send({ message: 'User was registered successfully!' });
avoid exclamation. use fullstop for neutral and professional tone.

2023-06-06 03:24 UTC, merged